language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - /^greenkeeper.*$/
# before_install:
#   - ./scripts/run-on-node-version.sh 11 "npm install -g greenkeeper-lockfile@1"
# before_script:
#   - ./scripts/run-on-node-version.sh 11 "greenkeeper-lockfile-update"
script:
  - npm run verify
# after_success:
#   - npm install -g travis-deploy-once@4
#   - ./scripts/run-on-node-version.sh 11 "npx codecov"
  - ./scripts/run-on-node-version.sh 11 "npm install -g codacy-coverage && cat ./coverage/lcov.info | codacy-coverage"
  - ./scripts/run-on-node-version.sh 11 "npm install -g coveralls && cat ./coverage/lcov.info | coveralls"
#   - travis-deploy-once "npm run semantic-release"
# after_script:
#   - ./scripts/run-on-node-version 11 "greenkeeper-lockfile-upload"
